language: node_js
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/registration_app

node_js:
  - 12
before_script:
  - psql -c 'create database registration_app;' -U postgres
  - psql -U postgres -d registration_app -a -f database.sql
services:
  - postgresql
addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-server-dev-9.4